### ISSUE TITLE
Schemas for themes

### ISSUE THREAD

**Issue by dheerajvs** [gatsbymanor/gatsby-theme-kit#13]
When I first encountered Manor and Jay, I expected it to define a set of schemas for data. Otherwise, how can one switch themes and still render the same data? But the docs don't seem to mention the expected constraints on data structures at all, leaving me confused as to how themes work.

My expectations seems to be inline with @KyleAMathews comment [here](https://github.com/gatsbyjs/gatsby/issues/4236#issuecomment-368603569):

> ...the idea of "themes" don't make sense unless you have a fixed data structure. Themes need to know what data is available and in what form. Otherwise you can't switch themes or upgrade themes independent of a site's data.

And the follow up [comment](https://github.com/gatsbyjs/gatsby/issues/4236#issuecomment-368609217):

> Because Gatsby has no default structure, we can't have true themes without a new schema layer that themes can rely on.

So, what are the implicit constraints on data structures and file organization that Jay expects?

**Comment by nodox** [comment]
I know this might not satisfactory but I'm making it up as I go therefore I don't want to give you an answer that will become out of date in a short amount of time 😅
