### ISSUE TITLE
src directory deleted on unmounting/mounting theme

### ISSUE THREAD

**Issue by Jaikant** [gatsbymanor/gatsby-theme-kit#2]
This is nice.

It would have been awesome if the themes were an 'npm install' after `gatsby new`.
Or integrated within Gatsby. Nevertheless good job on this!

When I tried running the project the `src` directory gets deleted on un-mounting and mounting a theme.

**Comment by nodox** [comment]
Hey thanks for the positive vibes @Jaikant  ❤️ 

Now the problem with npm install is that the theme would be installed in the `node_modules` folder. There are a few reasons why we do not want that to occur. 

1. We want the file visible in our working directory, not hidden away in the untracked `node_modules` folder.
2. We want to be able to freely edit the files. Customizable themes are at the core of this project.

At its core Jay is a filesystem tool. To unmount the current theme, we basically rename and move the `src` folder into the themes folder under a different name. Therefore there will be no `src` folder after unmounting.

To your point though a better experience might be to do more cloning and leave the directories sorta in tack however then we might not be sure that something happened. However, if your `src` folder does not reappear after mounting then that might be an actual problem. If thats the case, please post the steps to reproduce.

Feel free to make a PR if you think we can make this experience better. I'm glad you like it!

**Comment by Jaikant** [comment]
@nodox Thanks for your quick response!
I installed the gatsby-jay cli globally.
I then followed the procedure of `git clone`, `yarn`, followed by the unmount and mount of the theme. The src folder did not come back after I did the `mount` and so `gatsby develop` could not start.

I then manually created the `src` folder and the `pages` folder and put in sample react component.
I tried running `gatsby develop` but it error'ed as it couldn't find a template component i guess ...

Not sure what I am doing wrong.

**Comment by nodox** [comment]
I think you need to run these commands. The step you are missing I believe is the `add` step. Add is responsible for cloning down to your local themes directory. Try these steps @Jaikant 

```
$  jay unmount starter
$  jay add identity
$  jay mount identity
```

**Comment by Jaikant** [comment]
Nice it works now! I had done this earlier too, but maybe there was something stale in my project.
So we can port any theme to Gatsby Manor? Do you have any documentation on how we can do that? (Probably a separate issue/ask :)

**Comment by Jaikant** [comment]
...and I found the documentation to make themes! Thanks :)
I will try this for a project I am going to work on next week, for a friend's website.

**Comment by nodox** [comment]
Awesome! Let us about the final result on Twitter [@TheGatsbyManor](https://Twitter.com/thegatsbymanor). 😄
