### ISSUE TITLE
Follwing getting started section with fresh project cause error.

### ISSUE THREAD

**Issue by alishir** [gatsbymanor/gatsby-theme-kit#3]
I follow getting started section line by line, but after mounting identity theme, the following error occurred.
```
ERROR  Failed to compile with 1 errors                                                                                       07:51:30

This dependency was not found:

* /blogs/theme-test/src/templates/post.js in ./.cache/sync-requires.js

To install it, you can run: npm install --save /blogs/theme-test/src/templates/post.js
```

**Comment by nodox** [comment]
I just fixed this issue while working with someone else. Can you start over and let me know if you still see this issue?

**Comment by alishir** [comment]
I should start from development branch or just issue `yarn update`?

**Comment by nodox** [comment]
Delete the current project. Start from the beginning of the guide.
This is will be easiest as It might take forever to debug from where you are now without my looking at your screen. Basically I had a template with the wrong name on the repo but you must've cloned it minutes before I fixed it. 😅

**Comment by alishir** [comment]
Thanks, I will test it.

**Comment by alishir** [comment]
Thanks @nodox, I tested it and issue resolved.
